---
name: hspec-junit-formatter
version: 1.1.0.2
github: "freckle/hspec-junit-formatter"
license: MIT
author: "Freckle R&D"
maintainer: "engineering@freckle.com"
copyright: "2021 Renaissance Learning Inc"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - tests/golden*.xml

category: Testing
synopsis: A JUnit XML runner/formatter for hspec
description: Allows hspec tests to write JUnit XML output for parsing in various tools.

dependencies:
  - base < 5

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - conduit
    - containers
    - directory
    - exceptions
    - filepath
    - hspec-core >= 2.8.1
    - iso8601-time
    - text
    - time
    - xml-conduit
    - xml-types

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts -O0 "-with-rtsopts=-N"
    dependencies:
      - containers
      - filepath
      - hspec
      - hspec-junit-formatter
      - temporary
      - text
      - xml-conduit
  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - hspec
      - hspec-junit-formatter
      - markdown-unlit
