name: hspec-junit-formatter
version: 1.0.0.0 # maintained by semantic-release
github: "freckle/hspec-junit-formatter"
license: MIT
author: "Freckle R&D"
maintainer: "engineering@freckle.com"
copyright: "2021 Renaissance Learning Inc"

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - tests/golden/**/*.xml

category: Testing
synopsis: A JUnit XML runner/formatter for hspec
description: |
  Allows hspec tests to write JUnit XML output for parsing in various tools.

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
  - condition: "impl(ghc >= 9.2)"
    ghc-options:
      - -Wno-missing-kind-signatures

dependencies:
  - base < 5

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoPostfixOperators
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - array
    - conduit
    - directory
    - filepath
    - hspec-api
    - hspec-core >= 2.10.0 # modifyConfig
    - iso8601-time
    - mtl
    - regex-base
    - regex-tdfa
    - semigroups
    - text
    - time
    - xml-conduit
    - xml-types

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N"
    dependencies:
      - filepath
      - hspec
      - hspec-junit-formatter
      - temporary
      - text
      - xml-conduit >= 1.10.0.0 # rsPretty moved to .Internal module
  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - hspec
      - hspec-junit-formatter
    build-tools:
      - markdown-unlit
