---
name: hspec-junit-formatter
version: 1.0.0.4
github: "freckle/hspec-junit-formatter"
license: MIT
author: "Freckle R&D"
maintainer: "engineering@freckle.com"
copyright: "2021 Renaissance Learning Inc"

extra-source-files:
  - README.md
  - CHANGELOG.md
category: Testing
synopsis: A JUnit XML runner/formatter for hspec
description: Allows hspec tests to write JUnit XML output for parsing in various tools.

dependencies:
  - base < 5

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - conduit
    - containers
    - directory
    - exceptions
    - hashable
    - hspec-core
    - resourcet
    - temporary
    - text
    - xml-conduit
    - xml-types
