resolver: lts-19.1

ghc-options:
  "$locals": -fhide-source-paths
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-import-lists
    -Wno-prepositive-qualified-module
    -Wno-missing-safe-haskell-mode
