resolver: lts-17.11

extra-deps:
  - hspec-core-2.8.1
  - hspec-2.8.1
allow-newer: true

ghc-options:
  "$locals":
    -fhide-source-paths
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-import-lists
    -Wno-prepositive-qualified-module
    -Wno-missing-safe-haskell-mode
