name: Release

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - id: tag
        uses: freckle/haskell-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.tag.outputs.tag
        name: "Release to Hackage"
        run: stack --stack-yaml stack-lts-12.26.yaml upload --pvp-bounds lower .
        env:
          HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}
